homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 365
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: https://hassio.dillman.us:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: YRWeather
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - dewpointTemperature

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Ecobee Configuration
ecobee:
  api_key: !secret ecobee_api_key

# Denon Receiver Configuration
media_player:
  - platform: denonavr
    name: Denon AVR-X2000
    show_all_sources: True
    zones:
      - zone: Zone2
        name: Porch Speakers

# PocketCasts Configuration
sensor 2:
  - platform: pocketcasts
    username: !secret pocketcasts_username
    password: !secret pocketcasts_password

# MyQ Garage Door Configuration
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

# HASS.io Raspberry Pi System Monitor
sensor 3:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: since_last_boot

# IFTTT Configuration using Webhooks
ifttt:
  key: !secret ifttt_api_key

# MQTT Broker (mostly for SmartThings)
# Subscribed Topics: info: Subscribing to smartthings/Family Room Temp/Humidity/Motion/Light Sensor/temperature/cmd, smartthings/Basement Door Light/level/cmd, smartthings/Family Room Fan/level/cmd, smartthings/Family Room Fan Light/level/cmd, smartthings/Family Room Lamp/level/cmd, smartthings/Master Bedroom Fan Light/level/cmd, smartthings/Screened Porch Light/level/cmd, smartthings/Family Room Minimote/button/cmd, smartthings/Aeon Minimote - Master Bedroom/button/cmd, smartthings/Aeon HEM v1/power/cmd, smartthings/Family Room Temp/Humidity/Motion/Light Sensor/motion/cmd, smartthings/Family Room Temp/Humidity/Motion/Light Sensor/humidity/cmd, smartthings/Family Room Temp/Humidity/Motion/Light Sensor/illuminance/cmd, smartthings/Basement Door Light/switch/cmd, smartthings/Family Room Fan/switch/cmd, smartthings/Family Room Fan Light/switch/cmd, smartthings/Family Room Lamp/switch/cmd, smartthings/Front Light Switch/switch/cmd, smartthings/GE Outdoor Plug #2/switch/cmd, smartthings/GE Outdoor Plug #1/switch/cmd, smartthings/GE Outdoor Plug #3/switch/cmd, smartthings/Master Bedroom Fan Light/switch/cmd, smartthings/Screened Porch Light/switch/cmd, smartthings/Garage Door Sensor/contact/cmd, smartthings/Contacts/notify/cmd, smartthings/System/notify/cmd, smartthings/Aeon HEM v1/battery/cmd, smartthings/Family Room Temp/Humidity/Motion/Light Sensor/battery/cmd, smartthings/Garage Door Sensor/battery/cmd, smartthings/Rachel's iPhone/presence/cmd, smartthings/Jeremy's Phone/presence/cmd, smartthings/Aeon HEM v1/energy/cmd
mqtt:
  broker: 172.17.0.1
  port: 1883

# Light Switches
light:
  platform: mqtt
  name: "Family Room Fan Light"
  state_topic: "smartthings/Family Room Fan Light/switch/state"
  command_topic: "smartthings/Family Room Fan Light/switch/set"
  brightness_state_topic: "smartthings/Family Room Fan Light/level/state"
  brightness_command_topic: "smartthings/Family Room Fan Light/level/set"
  brightness_scale: 99
  payload_on: "on"
  payload_off: "off"
  retain: true

light 2:
  platform: mqtt
  name: "Basement Door Light"
  state_topic: "smartthings/Basement Door Light/switch/state"
  command_topic: "smartthings/Basement Door Light/switch/set"
  brightness_state_topic: "smartthings/Basement Door Light/level/state"
  brightness_command_topic: "smartthings/Basement Door Light/level/set"
  brightness_scale: 99
  payload_on: "on"
  payload_off: "off"
  retain: true

light 3:
  platform: mqtt
  name: "Master Bedroom Fan Light"
  state_topic: "smartthings/Master Bedroom Fan Light/switch/state"
  command_topic: "smartthings/Master Bedroom Fan Light/switch/set"
  brightness_state_topic: "smartthings/Master Bedroom Fan Light/level/state"
  brightness_command_topic: "smartthings/Master Bedroom Fan Light/level/set"
  brightness_scale: 99
  payload_on: "on"
  payload_off: "off"
  retain: true

light 4:
  platform: mqtt
  name: "Screened Porch Light"
  state_topic: "smartthings/Screened Porch Light/switch/state"
  command_topic: "smartthings/Screened Porch Light/switch/set"
  brightness_state_topic: "smartthings/Screened Porch Light/level/state"
  brightness_command_topic: "smartthings/Screened Porch Light/level/set"
  brightness_scale: 99
  payload_on: "on"
  payload_off: "off"
  retain: true

# Cell Phone Tracker from SmartThings
device_tracker:
  - platform: mqtt
    devices:
      jeremy_phone: "smartthings/Jeremy's Phone/presence/state"
      rachel_phone: "smartthings/Rachel's iPhone/presence/state"

# Perform Speedtest.net speed test at 2a, 8a, 2p and 8p
sensor 4:
  - platform: speedtest
    server_id: 9343
    hour:
      - 2
      - 8
      - 14
      - 20
    monitored_conditions:
      - ping
      - download
      - upload

# Rachio Sprinkler Configuration
switch:
  - platform: rachio
    access_token: !secret rachio_access_token

# Ring Video Doorbell Configuration
ring:
  username: !secret ring_username
  password: !secret ring_password

#camera:
#  - platform: ring

binary_sensor:
  - platform: ring

sensor 5:
  - platform: ring

